import localFont from "next/font/local";
import "./globals.css";
import dynamic from 'next/dynamic';
// components 
import SideBar from "@/components/sidebar/sidebar";
import InstallBootstrap from "@/components/bootstrap/InstallBootstrap";
import Navigationbar from "@/components/navbar/Navbar";
//import StoreProvider from "./GlobalRedux/provider";

const StoreProvider = dynamic(() => import('./GlobalRedux/provider'), {ssr: false})
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Pacific Ocean Portal",
  description: "Generated by create next app",
};

const topContent = <h1>About Us</h1>;
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <StoreProvider>
      <Navigationbar mainContent={children}/> 
      </StoreProvider>
        {/* bootstrap  */}
        <InstallBootstrap />
      </body>
    </html>
  );
}
